# CH08.예외처리
## 예외처리(exception handling)
### 프로그램 오류  
```text
- 컴파일 에러: 컴파일 시에 발생하는 에러
- 런타임 에러: 실행 시에 발견되는 에러
- 논리적 에러: 실행은 되지만, 의도와 다르게 동작하는 것
```
소스파일을 컴파일하면 컴파일러가 소스코드`(*.java)`에 대해 기본적인 검사를 수행하여 오타나, 잘못된 구문 등의 오류가 있는지 알려 준다.  
컴파일러가 알려 준 에러들을 모두 수정해서 컴파일을 성공적으로 마치고 나면, 클래스 파일`(*.class)`이 생성되고, 생성된 클래스 파일을 실행할 수 있는 것이다.  
그러나 컴파일을 성공적으로 마쳤더라도 프로그램 실행 도중 런타임 에러가 발생할 수 있다. 
런타임 에러를 방지하기 위해 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에 대한 대비를 하는 것이 필요하다. 
자바에서는 실행 시 발생할 수 있는 프로그램 오류를 '에러'와 '예외', 두 가지로 구분하였다.  
```text
- 에러(error): 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외(exception): 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
```
<br>

### 예외 클래스의 게층구조  
![image](https://user-images.githubusercontent.com/54930365/212794287-c30a3245-8d0f-4fc4-90ce-4953c4c10476.png)
앞서 배운 것처럼 모든 클래스의 조상은 Object 클래스이므로 Exception과 Error 클래스 역시 Object 클래스의 자손들이다.  

**Exception 클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로서, 프로그램의 사용자들의 동작에 의해서 발생하는 경우가 많다.**  
`ex) 배열의 범위를 벗어나는 경우(ArrayIndexOutOfBoudsException), 값이 null인 참조변수의 멤버를 호출하려 했다던가(NullPointerException), 클래스들 간의 형변환을 잘한 경우(ClassCastException), 정수를 0으로 나누려는 경우(ArithmeticException)`  
**RuntimeException 클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다.**  
`ex) 존재하지 않는 파일의 이름을 입력한 경우(FileNotFoundException), 실수로 클래스의 이름을 잘못 적은 경우(ClassNotFoundException), 입력한 데이터 형식이 잘못된 경우(DataFormatException)`  

### 예외 처리하기 - try-catch문  
프로그램의 실행도중에 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머가 이에 대한 처리를 미리 해주어야 한다.  
```text
- 예외처리의 정의: 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
- 예외처리의 목적: 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
```
발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기(UncaughtExceptionHandler)'가 받아서 예외의 원인을 화면에 출력한다.  

예외를 처리하기 위해서는 try-catch문을 사용하며, 그 구조는 다음과 같다.  
```java
try {
    // 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
    // Exception1이 발생한 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception2 e2) {
    // Exception2가 발생한 경우, 이를 처리하기 위한 문장을 적는다.
}
```
<br>

### 예외의 발생과 catch 블럭
catch 블럭은 괄호()와 블럭{} 두 부분으로 나눠져 있는데, 괄호() 내에는 처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언해야한다.  
예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어 진다.  
첫 번째 catch블럭부터 차례로 내려가면서 catch 블럭의 괄호() 내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof연산자를 이용해서 검사하게 되는데, 
검사결과가 true인 catch 블럭을 만날 때까지 검사는 계속된다.  
모든 예외 클래스는 Exception 클래스의 자손이므로, catch 블럭의 괄호()에 Exception 클래스 타입으 참조변수를 선언해 놓으면 어떤 종류의 예외가 발생하더라도 이 catch 블럭에 의해서 처리된다.  

### printStackTrace()와 getMessage()  
예외가 발생했을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨 있으며, getMessage()와 printStackTrace()를 통해서 이 정보들을 얻을 수 있다.  
```text
- printStackTrace(): 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
- getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
```
