# CH08.예외처리
## 예외처리(exception handling)
### 프로그램 오류  
```text
- 컴파일 에러: 컴파일 시에 발생하는 에러
- 런타임 에러: 실행 시에 발견되는 에러
- 논리적 에러: 실행은 되지만, 의도와 다르게 동작하는 것
```
소스파일을 컴파일하면 컴파일러가 소스코드`(*.java)`에 대해 기본적인 검사를 수행하여 오타나, 잘못된 구문 등의 오류가 있는지 알려 준다.  
컴파일러가 알려 준 에러들을 모두 수정해서 컴파일을 성공적으로 마치고 나면, 클래스 파일`(*.class)`이 생성되고, 생성된 클래스 파일을 실행할 수 있는 것이다.  
그러나 컴파일을 성공적으로 마쳤더라도 프로그램 실행 도중 런타임 에러가 발생할 수 있다. 
런타임 에러를 방지하기 위해 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에 대한 대비를 하는 것이 필요하다. 
자바에서는 실행 시 발생할 수 있는 프로그램 오류를 '에러'와 '예외', 두 가지로 구분하였다.  
```text
- 에러(error): 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외(exception): 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
```
<br>

### 예외 클래스의 게층구조  
![image](https://user-images.githubusercontent.com/54930365/212794287-c30a3245-8d0f-4fc4-90ce-4953c4c10476.png)
앞서 배운 것처럼 모든 클래스의 조상은 Object 클래스이므로 Exception과 Error 클래스 역시 Object 클래스의 자손들이다.  

**Exception 클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로서, 프로그램의 사용자들의 동작에 의해서 발생하는 경우가 많다.**  
`ex) 배열의 범위를 벗어나는 경우(ArrayIndexOutOfBoudsException), 값이 null인 참조변수의 멤버를 호출하려 했다던가(NullPointerException), 클래스들 간의 형변환을 잘한 경우(ClassCastException), 정수를 0으로 나누려는 경우(ArithmeticException)`  
**RuntimeException 클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다.**  
`ex) 존재하지 않는 파일의 이름을 입력한 경우(FileNotFoundException), 실수로 클래스의 이름을 잘못 적은 경우(ClassNotFoundException), 입력한 데이터 형식이 잘못된 경우(DataFormatException)`  

### 예외 처리하기 - try-catch문  
프로그램의 실행도중에 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머가 이에 대한 처리를 미리 해주어야 한다.  
```text
- 예외처리의 정의: 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
- 예외처리의 목적: 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
```
발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기(UncaughtExceptionHandler)'가 받아서 예외의 원인을 화면에 출력한다.  

예외를 처리하기 위해서는 try-catch문을 사용하며, 그 구조는 다음과 같다.  
```java
try {
    // 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
    // Exception1이 발생한 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception2 e2) {
    // Exception2가 발생한 경우, 이를 처리하기 위한 문장을 적는다.
}
```
<br>

### 예외의 발생과 catch 블럭
catch 블럭은 괄호()와 블럭{} 두 부분으로 나눠져 있는데, 괄호() 내에는 처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언해야한다.  
예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어 진다.  
첫 번째 catch블럭부터 차례로 내려가면서 catch 블럭의 괄호() 내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof연산자를 이용해서 검사하게 되는데, 
검사결과가 true인 catch 블럭을 만날 때까지 검사는 계속된다.  
모든 예외 클래스는 Exception 클래스의 자손이므로, catch 블럭의 괄호()에 Exception 클래스 타입으 참조변수를 선언해 놓으면 어떤 종류의 예외가 발생하더라도 이 catch 블럭에 의해서 처리된다.  

### printStackTrace()와 getMessage()  
예외가 발생했을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨 있으며, getMessage()와 printStackTrace()를 통해서 이 정보들을 얻을 수 있다.  
```text
- printStackTrace(): 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
- getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
```

<br>

### 멀티 catch 블럭  
JDK 1.7부터 여러 catch 블럭을 '|'기호를 이용해서, 하나의 catch 블럭으로 합칠 수 있게 되었으며, 이를 `멀티 catch 블럭`이라 한다.  
'멀티 catch 블럭'을 이용하면 중복된 코드를 줄일 수 있다. 그리고 '|' 기호로 연결할 수 있는 예외 클래스의 개수에는 제한이 없다.  
```java
ex)
try{
    ...
} catch (ExceptionA | ExceptionB e) {
    e.printStackTrace();
}
```
만일 멀티 catch블럭의 '|' 기호로 연결된 예외 클래스가 조상과 자손의 관계에 있다면 컴파일 에러가 발생한다. 이는 조상 클래스만 써주는 것과 똑같기 때문에 불필요한 코드는 제거하라는 의미에서 에러가 발생하는 것이다.  

필요하다면 instanceof로 어떤 예외가 발생한 것인지 확인하고 개별적으로 처리할 수 있다. 그러나 이렇게까지 해가면서 catch 블럭을 합칠 일은 거의 없을 것이다.  
```java
try{
    ...
} catch (ExceptionA | ExceptionB e) {
    e.methodA();    // 에러. ExceptionA에 선언된 methodA()는 호출 불가.
        
    if(e instanceof ExceptionA) {
        ExceptionA e1 = (ExceptionA) e;
        e1.methodA();   // OK. ExceptionA에 선언된 메서드 호출가능.
    }    
}
```

마지막으로 멀티 catch 블럭에 선언된 참조변수 e는 상수이므로 값을 변경할 수 없다는 제약이 있다.  
이것은 여러 catch 블럭이 하나의 참조변수를 공유하기 때문에 생기는 제약으로 실제로 참조변수의 값을 바꿀 일은 없을 것이다.  


### 예외 발생시키기  
키워드 throw를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있으며, 방법은 아래의 순서를 따르면 된다.  
```text
1. 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
    Exception e = new Exception("고의로 발생시켰음");
2. 키워드 throw를 이용해서 예외를 발생시킨다.
    throw e;
```

Exception 인스턴스를 생성할 때, 생성자에 String을 넣어 주면, 이 String이 Exception 인스턴스에 메시지로 저장된다. 이 메시지는 getMessage()를 이용해 얻을 수 있다.  
Exception이 발생할 가능성이 있는 문장들에 대해 예외처리를 해주지 않으면 컴파일조차 되지 않으므로 예외처리를 반드시 해줘야 한다.   
단, RuntimeException 클래스와 그 자손들(RuntimeException 클래스들의 자손들)에 해당하는 예외는 프로그래머에 의해 실수로 발생하는 것들이기 때문에 예외처리를 강제하지 않는다.  
컴파일러가 예외처리를 확인하지 않는 RuntimeException 클래스들은 `unchecked 예외`라고 부르고, 예외처리를 확인하는 Exception 클래스들은 `checked 예외`라고 부른다.   

### 메서드 예외 선언하기  
예외를 처리하는 방법에는 try-catch문을 사용하는 것 외에, 예외를 메서드에 선언하는 방법이 있다.  
메서드에 예외를 선언하려면, 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어주기만 하면 된다.  
예외를 발생시키는 키워드 `throw`와 예외를 메서드에 선언할 때 쓰는 `throws`를 잘 구별해야 한다.  

자바에서는 메서드를 작성할 때 메서드 내에서 발생할 가능성이 있는 예외를 메서드의 선언부에 명시하여 이 메서드를 사용하는 쪽에서 이에 대한 처리를 하도록 강요하기 때문에, 
프로그래머들의 짐을 덜어 주는 것은 물론이고 보다 견고한 프로그램 코드를 작성할 수 있도록 도와준다.  

메서드에 예외를 선언할 때 일반적으로 RuntimeException 클래스들은 적지 않는다. 
이 들을 메서드 선언부의 throws에 선언한다고 해서 문제가 되지 않지만, 보통 반드시 처리해주어야 하는 예외들만 선언한다.  

Java API 문서에서 메서드의 선언부와 'Throws:'를 보고, 이 메서드에서는 어떤 예외가 발생할 수 있으며 반드시 처리해주어야 하는 예외는 어떤 것들이 있는지 확인할 수 있다.  

사실 예외를 메서드의 throws에 명시하는 것은 예외를 처리하는 것이 아니라, 자신(예외가 발생할 가능성이 있는 메서드)을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것이다.  
예외를 전달받은 메서드가 또다시 자신을 호출한 메서드에게 전달할 수 있으며, 이런 식으로 계속 호출스택에 있는 메서드들을 따라 전달되다가 제일 마지막에 있는 main 메서드에서도 예외가 처리되지 않으면, main 메서드마저 종료되어 프로그램 전체가 종료된다.  

이처럼 예외가 발생한 메서드에서 예외처리를 하지 않고 자신을 호출한 메서드에게 예외를 넘겨줄 수는 있지만, 이것으로 예외가 처리되는 것은 아니고 예외를 단순히 전달만 하는 것이다. 결국 어느 한 곳에서는 반드시 try-catch문으로 예외처리를 해주어야 한다.   

### finally 블럭  
finally 블럭은 **예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적**으로 사용된다.  
try-catch-finally의 순서로 구성된다.  
try블럭과 catch블럭의 문장 수행 중에 return 문을 만나도 finally블럭의 문장들은 수행된다.   

### 자동 자원 반환 - try-with-resources문  
try-with-resources문의 괄호() 안에 객체를 생성하는 문장을 넣으면, 이 객체는 따로 close()를 호출하지 않아도 try블럭을 벗어나는 순간 자동적으로 close()가 호출된다. 
그 다음에 catch블럭 또는 finally블럭이 수행된다.
```java
ex) 괄호() 안에 객체를 생성하는 문장을 넣는다. 괄호() 안에 두 문장 이상 넣을 경우 ';'로 구분한다.
try (FileInputStream fis = new FileInputStream("score.dat");
        DataInputStream dis = new DataInputStream(fis)){
    ...
} catch (ExceptionA e) {
    ...
}
```
이처럼 try-with-resources문에 의해 자동으로 객체의 close()가 호출될 수 있으려면, 클래스가 AutoCloseable이라는 인터페이스를 구현한 것이어야만 한다.  


### 사용자정의 예외 만들기  
기존의 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 에외 클래스를 정의하여 사용할 수 있다. 
보통 Exception 클래스 또는 RuntimeException 클래스로부터 상속받아 클래스를 만들지만, 필요에 따라서 알맞은 예외 클래스를 선택할 수 있다.  

기존의 예외클래스는 주로 Exception을 상속받아서 `checked예외`로 작성하는 경우가 많았지만, 
요즘은 예외처리를 선택적으로 할 수 있도록 RuntimeException을 상속받아서 작성하는 쪽으로 바뀌어가고 있다. 
`checked예외`는 반드시 예외처리를 해주어야 하기 때문에 예외처리가 불필요한 경우에도 try-catch문을 넣어서 코드가 복잡해지기 때문이다.  
그래서 필요에 따라 예외처리의 여부를 선택할 수 있는 `unchecked예외`가 강제적인 `checked예외`보다 더 환영받고 있다.    

### 예외 되던지기(exception re-throwing)
한 메서드에서 발생할 수 있는 예외가 여럿인 경우, 몇 개는 try-catch문을 통해서 메서드 내에서 자체적으로 처리하고, 그 나머지는 선언부에 지정하여 호출한 메서드에서 처리하도록 함으로써, 
양쪽에서 나눠서 처리되도록 할 수 있다.  
그리고 심지어는 단 하나의 예외에 대해서도 예외가 발생한 메서드와 호출한 메서드, 양쪽에서 처리하도록 할 수 있다.  
이것은 예외를 처리한 후에 인위적으로 다시 발생시키는 방법을 통해서 가능한데, 이를 `예외던지기(exception re-throwing)`라고 한다.  


